{
  search: [
    {
      type:'link',
      query:'https://www.diigo.com/search?adSScope=my&what={{term}}&snapshot=no',
      translate:'parseHTML(response)',
      name:{
        selector:'.Titleinner',
        expression:'element.textContent.trim()'
      },
      link:{
        selector:'.Titleinner',
        expression:'element.firstElementChild.href'
      },
      description:{
        selector:'.Titleinner',
        expression:'element.textContent.trim()'
      }
    }
  ]
}